name: Deploy Hello World App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run Python app
      run: python app.py

  build-and-deploy-node:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Install dependencies
      run: npm install
    
    - name: Run Node.js app
      run: node app.js
